### ISSUE TITLE
Own image

### ISSUE THREAD

**Issue by MariasStory** [Zheng222/PPON#1]
Hi,
The results look good.
How do I use your code on my images?
Do I need to train?
Please provide simple instructions.
BZW: What about JPG artifacts?
Thanks

**Comment by vlad3996** [comment]
https://github.com/vlad3996/PPON/blob/master/demo.ipynb

**Comment by Zheng222** [comment]
@MariasStory If your test image with jpeg artifacts, I recommend that you collect the related training datasets to retrain the `content branch` of PPON.

**Comment by Zheng222** [comment]
@vlad3996 Thank you!

**Comment by riccardogiorato** [comment]
Hey why this was closed @Zheng222 ? 

Adding the simple inference demo would help new users a lot to be able to user your paper!
Is it possible to merge this and add the link in the README?

**Comment by ABDOELSHEMY** [comment]
@vlad3996 
thanks for your demo.ipynb file
how can i save the result as splitted images, when i run in google colab it give stacked images

**Comment by riccardogiorato** [comment]
@ABDOELSHEMY you can do with this code:

```python
from PIL import Image
out_c = Image.fromarray(out_c)
out_c.save("out_c.png")

out_s = Image.fromarray(out_s)
out_s.save("out_s.png")

out_p = Image.fromarray(out_p)
out_p.save("out_p.png")

from google.colab import files
files.download('out_c.png') 
files.download('out_s.png') 
files.download('out_p.png') 
```

**Comment by ABDOELSHEMY** [comment]
Hi @Giorat 
thank you very much for your code it works great, really thanks man

**Comment by ABDOELSHEMY** [comment]
@Giorat 
any idea to how to use folder of photos as input instead of 1 photo at time
thank you

**Comment by ABDOELSHEMY** [comment]
guys
Was anyone able to run this great Project in colab with entire folder, It is a long time now, and I could not do it despite all my attempts ,Any help would be greatly appreciated
