### ISSUE TITLE
how to retrain the model using  my own datasets？  thank you~

### ISSUE THREAD

**Issue by hiredd** [Zheng222/PPON#2]

**Comment by Zheng222** [comment]
@hiredd Hello, in the paper, the detailed training scheme has been provided. You can refer to this instruction.

**Comment by victorca25** [comment]
@hiredd I've made a partial implementation of the training code based on the paper here: https://github.com/victorca25/BasicSR

It's still missing some parts, but it may eventually get there (help would be appreciated :D)

**Comment by hiredd** [comment]
@Zheng222  @victorca25  thank  you ~~
