### ISSUE TITLE
Training code？

### ISSUE THREAD

**Issue by LeeHW-THU** [Zheng222/PPON#3]
can you upload training code？
thank you！

**Comment by victorca25** [comment]
While waiting for the official version, you can use my implementation of the training code based on the paper from here: https://github.com/victorca25/BasicSR

**Comment by Zheng222** [comment]
@LeeHW-TW The training code will be released when our manuscript is accepted by Journal.

**Comment by KevinTech0916** [comment]
I very much appreciate your work and want to learn more about it.
Hope to get training code soon :)

**Comment by Zheng222** [comment]
Training code has been uploaded now.
