### ISSUE TITLE
npy conversion

### ISSUE THREAD

**Issue by victorca25** [Zheng222/PPON#5]
Not an issue, but out of curiosity, why do the images have to be renamed “ 00xxxx.png ” and converted to npy? Is there a performance benefit?

**Comment by Zheng222** [comment]
@victorca25 
Hello, for convenient dataloading, the rename operation is necessary.
https://github.com/Zheng222/PPON/blob/1ae69893d6a1795c4b7ec9369a0078d1ca97761a/data/srdata.py#L65-L68

The purpose of converting png file to npy file is to improve the efficiency of data loading.

**Comment by victorca25** [comment]
Awesome! Thanks for the reply. I'm interested in testing the performance difference. 

Cheers and great job, thanks for sharing!
